//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parcial3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mensajes
    {
        public long IdMensajes { get; set; }
        public string MensajeDescripcion { get; set; }
        public long CostoMensaje { get; set; }
        public long ConversacionId { get; set; }
    
        public virtual Conversacion Conversacion { get; set; }
    }
}
